apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: pos-ticket-system-backend-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pos-ticket-system-backend-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80