apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: pos-ticket-system-backend-backendconfig
spec:
  timeoutSec: 60
  connectionDraining:
    drainingTimeoutSec: 65
  healthCheck:
    checkIntervalSec: 20
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /api/v1/health